name: Publish Executables

permissions:
  contents: read

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build executables
        run: |
          npm run build
          npm run build-exe

      - name: Attach artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: cli/*